// Generated by Xata Codegen 0.29.2. Please do not edit.
import { buildClient } from '@xata.io/client'
import type { BaseClientOptions, SchemaInference, XataRecord } from '@xata.io/client'

const tables = [
  {
    name: 'vectors',
    columns: [
      { name: 'contents', type: 'string' },
      { name: 'embedding', type: 'vector', vector: { dimension: 1536 } },
    ],
  },
] as const

export type SchemaTables = typeof tables
export type InferredTypes = SchemaInference<SchemaTables>

export type Vectors = InferredTypes['vectors']
export type VectorsRecord = Vectors & XataRecord

export type DatabaseSchema = {
  vectors: VectorsRecord
}

const DatabaseClient = buildClient()

const defaultOptions = {
  databaseURL: 'https://Rishi-Raj-Jain-s-workspace-80514q.us-east-1.xata.sh/db/rag-chatbot',
}

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables)
  }
}

let instance: XataClient | undefined = undefined

export const getXataClient = () => {
  if (instance) return instance

  instance = new XataClient()
  return instance
}
